"""Reflector — periodically consolidates an agent's lessons into LESSONS.md.

A background task (sibling of heartbeat/scheduler in main.py). Once per interval
per agent it gathers that agent's `category="lesson"` memories and makes ONE
cheap LLM call (Haiku by default) to dedupe and group them into a concise
LESSONS.md, which build_startup_context injects at the next session start.

Deliberately NOT a full agent turn: it runs in a neutral working dir (no
CLAUDE.md / .mcp.json), with no tools, so it's a single cheap completion.
"""

import asyncio
import logging
import os
import time
from pathlib import Path

from src.core import runtime_state
from src.core.base import Message, MessageRole

logger = logging.getLogger(__name__)

_SYSTEM = (
    "You are a memory-consolidation assistant for an AI agent. You are given the "
    "agent's saved lessons, each with a confidence score. Produce a concise "
    "LESSONS.md the agent reads at the start of future sessions.\n"
    "Rules: merge near-duplicates; drop noise; keep each lesson to one short "
    "bullet. Group into exactly these sections (omit a section if empty):\n"
    "## Preferred — confidence >= 0.80, things that reliably work; start here.\n"
    "## Tentative — confidence 0.40–0.79, seen useful but not yet corroborated.\n"
    "## Avoid / Dead ends — confidence < 0.40 or marked dead-end; do not retry.\n"
    "## Codify — lessons that describe a repeatable multi-step PROCEDURE the "
    "agent keeps re-doing by hand (a report pipeline, a fixed format, a "
    "recurring sequence of tool calls). One bullet each: name the procedure "
    "and what a skill for it would need to capture (inputs, steps, gotchas, "
    "output). Only procedures corroborated across lessons or confirmed by the "
    "user — never one-offs. The agent will propose these to the user as "
    "skills (see /codify).\n"
    "If a lesson contains [CORRECTION], state the corrected fact under Preferred.\n"
    "Output ONLY the markdown body (no ``` fences, no preamble)."
)


class Reflector:
    def __init__(self, agent_manager, config: dict | None = None):
        self.mgr = agent_manager
        cfg = config or {}
        self.enabled = cfg.get("enabled", True)
        self.model = cfg.get("model", "haiku")
        self.interval_h = float(cfg.get("interval_hours", 24))
        self.min_lessons = int(cfg.get("min_lessons", 3))
        self.tick = float(cfg.get("tick_seconds", 3600))

    def _due(self, agent_id: str, now: float) -> bool:
        last = runtime_state.get_flag(f"reflector_last_{agent_id}", 0) or 0
        return (now - float(last)) >= self.interval_h * 3600

    def _work_dir(self) -> str:
        """Neutral cwd for the LLM call — no agent CLAUDE.md/.mcp.json to load."""
        d = Path(os.environ.get("KBOTS_OVERLAY", ".")) / "tmp" / "reflector"
        d.mkdir(parents=True, exist_ok=True)
        return str(d)

    async def run(self) -> None:
        logger.info(f"Reflector started (model={self.model}, every {self.interval_h}h)")
        while True:
            try:
                if self.enabled:
                    now = time.time()
                    for agent_id in list(getattr(self.mgr, "agent_configs", {})):
                        if self._due(agent_id, now):
                            await self._reflect(agent_id)
                            runtime_state.set_flag(f"reflector_last_{agent_id}", time.time())
            except Exception as e:
                logger.error(f"Reflector tick failed: {e}", exc_info=True)
            await asyncio.sleep(self.tick)

    async def _reflect(self, agent_id: str) -> bool:
        memory = self.mgr._get_agent_memory(agent_id)
        if not memory or not hasattr(memory, "list_by_category"):
            return False
        lessons = await memory.list_by_category(agent_id, "lesson", limit=100)
        if len(lessons) < self.min_lessons:
            logger.debug(f"Reflector: {agent_id} has {len(lessons)} lessons "
                         f"(<{self.min_lessons}) — skipping")
            return False

        digest = "\n".join(
            f"- (confidence {float(m.get('confidence', 0.7) or 0.7):.2f}) "
            f"{(m.get('content') or '').strip()}"
            for m in lessons
        )
        try:
            llm = self.mgr._get_agent_llm(agent_id)
        except Exception:
            return False

        messages = [
            Message(role=MessageRole.SYSTEM, content=_SYSTEM),
            Message(role=MessageRole.USER, content=f"Agent's saved lessons:\n\n{digest}"),
        ]
        resp = await llm.complete(
            messages, tools=None, project_dir=self._work_dir(),
            model=self.model, timeout=180,
        )
        body = (resp.content or "").strip()
        if not body:
            return False

        header = ("# LESSONS\n\n> Auto-generated by the reflector — what has worked "
                  "and what to avoid. Consulted at the start of each session.\n\n")
        out = Path(self.mgr._get_project_dir(agent_id)) / "LESSONS.md"
        out.write_text(header + body + "\n")
        logger.info(f"Reflector wrote {out} for {agent_id} "
                    f"({len(lessons)} lessons, model={self.model})")
        return True
