#!/usr/bin/env bash
# install-systemd.sh — Symlink generated unit files into systemd and enable timers
# Called by setup.py after it generates unit files into <overlay>/systemd/.
#
# Usage: sudo bash scripts/install-systemd.sh <overlay-dir> [--enable-service]
#   <overlay-dir>       Path to the overlay directory (contains systemd/ subdir)
#   --enable-service    Also enable kbots.service (optional)
#
# What it does:
#   1. Symlinks all .service/.timer files from <overlay>/systemd/ to /etc/systemd/system/
#   2. Symlinks all .service/.timer files from config/timers/ (core health timers)
#   3. Runs daemon-reload
#   4. Enables all .timer units
#   5. Optionally enables kbots.service

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SYSTEMD_DIR="/etc/systemd/system"

if [ $# -lt 1 ]; then
    echo "Usage: sudo bash $0 <overlay-dir> [--enable-service]"
    exit 1
fi

OVERLAY="$1"
ENABLE_SERVICE=false
[ "${2:-}" = "--enable-service" ] && ENABLE_SERVICE=true

OVERLAY_SYSTEMD="$OVERLAY/systemd"
CORE_TIMERS="$PROJECT_ROOT/config/timers"

# --- Symlink core timer units ---
if [ -d "$CORE_TIMERS" ]; then
    for f in "$CORE_TIMERS"/*.service "$CORE_TIMERS"/*.timer; do
        [ -f "$f" ] || continue
        name=$(basename "$f")
        # Skip if overlay has an override for this unit
        [ -f "$OVERLAY_SYSTEMD/$name" ] && continue
        ln -sf "$f" "$SYSTEMD_DIR/$name"
        echo "  core   $name"
    done
fi

# --- Symlink overlay units (generated by setup.py) ---
if [ -d "$OVERLAY_SYSTEMD" ]; then
    for f in "$OVERLAY_SYSTEMD"/*.service "$OVERLAY_SYSTEMD"/*.timer; do
        [ -f "$f" ] || continue
        name=$(basename "$f")
        ln -sf "$f" "$SYSTEMD_DIR/$name"
        echo "  overlay $name"
    done
fi

# --- Reload ---
systemctl daemon-reload

# --- Enable timers ---
for f in "$CORE_TIMERS"/*.timer "$OVERLAY_SYSTEMD"/*.timer; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    systemctl enable --now "$name" 2>/dev/null || true
done

# --- Optionally enable main service ---
if $ENABLE_SERVICE && [ -f "$OVERLAY_SYSTEMD/kbots.service" ]; then
    systemctl enable kbots.service
    echo "  kbots.service enabled"
fi

echo "Systemd units installed."
